title:            Flying Disc Dogs of Austin
tagline:          Strengthening the Bond Between Human and Dog through Play, Teamwork and Trust
description:      Disc dogs in Austin

# Owner/author information
owner:
  name:           Flying Disc Dogs of Austin
  avatar:         icon.jpg
  email:          fddadogs@gmail.com
  location:       "Austin, TX"

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Chicago
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

assets: /assets/

sass:
    sass_dir: /assets/css/partials/
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /FDDA-site/:categories/:title
baseurl: "/FDDA-site/"

collections:
  events:
    output: true
