title:            Flying Disc Dogs of Austin
tagline:          Strengthening the Bond Between Human and Dog through Play, Teamwork and Trust
description:      Disc dogs in Austin

# Owner/author information
owner:
  name:           Flying Disc Dogs of Austin
  avatar:         icon.jpg
  email:          fddadogs@gmail.com
  location:       "Austin, TX"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:           en_US

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /index
  - title: About
    url: /about
  - title: Join
    url: /join
  - title: Events
    url: /events
  - title: Book
    url: /book

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Chicago
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
